Add database
RedStarMisha/java-filmorate pull request #11
Opened 2022-07-19 13:38 UTC by RedStarMisha

2022-07-19 14:30 UTC, EugeneLenkevich requested changes
Привет,  Михаил, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-07-19 14:30 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/filmservice/FilmServiceBD.java
> +    public FilmServiceBD(FilmStorage filmStorage, FilmsRatingStorage filmsRating) {
Можно не задавать руками конструктор, можно добавить аннотацию lombok @RequiredArgsConstroctor

2022-07-19 14:30 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/filmservice/FilmServiceBD.java
> +        List<Long> popularityFilmsId = filmsRating.getPopularFilms(count);
А не проще сделать все это одним запросом? На уровне БД это делается гораздо эффективнее, да и код станет покрасивее :)

select * from films where film_id in (elect film_id from FILM_RESPECT_FROM_USER ... )

2022-07-19 14:30 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/userservice/UserServiceBD.java
> +            e.printStackTrace();
Если писать логи в таком виде то они потеряются, используй объект log, он у тебя есть (@Slf4j =)

2022-07-19 14:30 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/userservice/UserServiceImpl.java
> +//        user.addFriend(userId);
Закомментированный код не стоит оставлять, толку от него никакого :)

2022-07-19 14:30 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorageDao.java
> +                e.printStackTrace();
Опять таки, стоит везде использовать объект log, этот вывод в консоль в итоге потеряется :)

2022-07-20 13:29 UTC, RedStarMisha commented on src/main/java/ru/yandex/practicum/filmorate/service/filmservice/FilmServiceBD.java
> +        List<Long> popularityFilmsId = filmsRating.getPopularFilms(count);
т.е маппинг лучше делать на уровне бд, да?

2022-07-20 17:26 UTC, EugeneLenkevich requested changes
Привет, Михаил, спасибо за PR

2022-07-20 17:32 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/filmservice/FilmServiceBD.java
> +        List<Long> popularityFilmsId = filmsRating.getPopularFilms(count);
Маппинг - это когда мы из одной сущности перекладываем данные
Тут же речь об обработке данных.  И, таки да, данные лучше обрабатывать на стороне БД, субд это умеют делать гораздо быстрее и гораздо проще, могут оперировать гораздо большими объемами данных чем мы можем запихнуть в память нашего приложения, плюс есть индексы и прочие оптимизации производительности :)

2022-07-21 07:18 UTC, EugeneLenkevich approved these changes
Все супер, спасибо!

2022-09-08 07:35 UTC, merged