Add friends likes
RedStarMisha/java-filmorate pull request #9
Opened 2022-06-22 09:13 UTC by RedStarMisha

2022-06-22 16:23 UTC, eugene-lenkevich requested changes
Привет, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-06-22 16:23 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        this.filmStorage = filmStorage;
Контроллер все же пусть зависит только от сервиса, а вот сервис зависит от хранилища (storage), тогда у нас будут слои: уровень контроллера, уровень бизнес-логики и уровень хранилища данных. Иначе у нас контроллер оказывается жестко связанным с деталями реализации нижележащих слоев. 
В общем, давай связь с storage отсюда уберем и будем к нему обращаться через методы сервиса  :)

2022-06-22 16:23 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/EntityIsNotExistingException.java
> +public class EntityIsNotExistingException extends RuntimeException {
А подходит ли для данной ситуации непроверяемое исключение?
Пользователь запросил несуществующие данные - вполне себе штатная ситуация, пусть тут будет проверяемое исключение :)
extends Exception

2022-06-23 09:14 UTC, RedStarMisha commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (userId == null) {
в данном случае это проверка какой URI запрашивается( делал как в 5.1 https://www.baeldung.com/spring-pathvariable). или так никто не делает?

2022-06-23 09:45 UTC, RedStarMisha commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/EntityIsNotExistingException.java
> +public class EntityIsNotExistingException extends RuntimeException {
Из-за смены на проверяемое исключение пришлось проверять переменную idToUserFunction в классе UserService блоком try-catch. Выглядит конечно уродски эта история ))

2022-06-23 11:11 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (userId == null) {
Делают как попало на самом деле =)
Ок, пусть так остается

2022-06-23 11:25 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/EntityIsNotExistingException.java
> +public class EntityIsNotExistingException extends RuntimeException {
Ну все верно, лябда - это на самом деле метод анонимного класса, у него, в смысле у метода класса, исключение должно быть прописано в throws чтобы компилятор не ругался. Но тогда возникнет проблемка со стримами, может замечал, из которых нельзя выкидывать проверяемые исключения (почему - можно посмотреть как заданы функциональные интерфейсы, они не кидают исключений). Потому в качестве костыля выкидывают непроверяемые исключения, но это костыль. 
Как его обойти. 
На самом деле не надо изначально кидать исключений, например, если не найдена запись в БД, то возвращать Optiona.empty() а не кидать какой нибудь UserNotFoundException и тд и тп. Ну или да, обрамлять try-catch, некрасиво но в принципе норм. Давай так и оставим try-catch иначе много переделывать придеться. Суть, на самом деле, в том, что не надо лепить слишком много исключений, если есть возможность обойтись без них, то лучше обойтись, эта ситуация - яркий пример :)

В Spring JPA такое делается обычно вот так

![image](https://user-images.githubusercontent.com/94845100/175287927-8798dd2c-0dba-495b-9c15-a617ebd9dcb7.png)

2022-06-23 11:26 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (userId == null) {
Метод сервиса может дернуть какой то другой код. Если в методе сервиса есть такая обработка (null) то ок :)

2022-06-23 11:27 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-07-01 09:48 UTC, merged